### ISSUE TITLE
JavaScript does not support function overloading

### ISSUE THREAD

**Issue by ariovistus** [2729StormRobotics/tba-storm-node#7]
pretty sure javascript doesn't do function overloading

getTeamList
getTeamEventListSimple

and some others

**Comment by TomOrth** [comment]
They aren't duplicates. Each function makes a call to a different TBA (thebluealliance) endpoint.

**Comment by ariovistus** [comment]
the method names are the same. I think the later one will overwrite the first one?

**Comment by rjbohinski** [comment]
@TomOrth, @ariovistus is probably right. The functions are defined multiple times and are overwritten.

See:
[getTeamList(pageNum)](https://github.com/2729StormRobotics/tba-api-storm/blob/4a0d292cf8d90a8141be295cf1fa7a2c0f2d46b4/tba-storm.js#L33)
[getTeamList(year, pageNum)](https://github.com/2729StormRobotics/tba-api-storm/blob/4a0d292cf8d90a8141be295cf1fa7a2c0f2d46b4/tba-storm.js#L41)

**Comment by rjbohinski** [comment]
@ariovistus pull request #10 should patch this. Please let us know if this resolves your issue.

**Comment by rjbohinski** [comment]
Closing this as it should be fixed. Feel free to reopen it if you have any issues.
